import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import { faCoffee, faDroplet, faLocationDot, faMagnifyingGlass, faWind } from '@fortawesome/free-solid-svg-icons'
import ReactCountryFlag from "react-country-flag"

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Weather now!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Ubuntu:ital,wght@0,300;0,400;0,500;0,700;1,300;1,400;1,500;1,700&display=swap" rel="stylesheet"/>
        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.1/css/all.min.css" integrity="sha512-MV7K8+y+gLIBoVD59lQIYicR65iaqukzvf/nwasF0nqhPay5w/9lJmVM2hMDcnK1OnMGCdVK+iQrJ7lzPJQd1w==" crossorigin="anonymous" referrerpolicy="no-referrer" />
        {/*85ada20ccacae8d4b403694291e77737 https://api.openweathermap.org/data/2.5/weather?lat={lat}&lon={lon}&appid=85ada20ccacae8d4b403694291e77737 */}
      </Head>

      <main className="main">

        <div className="container">
          <div className="form">
            <h1>Check the weather of a city!</h1>
            <div className="form_input_container">
              <input type="text"
              placeholder="Type the name of the city"
              id="city-input" 
              />
              <button id="search">
                
              <FontAwesomeIcon icon={faMagnifyingGlass}/>
              
              </button>
            </div>
          </div>

          <div id="weather-data">
            <h2><FontAwesomeIcon icon={faLocationDot} className="icon"/> 
              <span id="city">Maceió</span>
              <ReactCountryFlag countryCode="USi" />
            </h2>
            <p id="temperature"> <span>38</span>&deg;C</p>
            <div id="description-container">
              <p id="description">Nublado</p>
              <img src="https://countryflagsapi.com/png/alb" alt="weather now" id="weather-icon" />
            </div>
            <div id="details-container">
              <p id="umidity">
              <FontAwesomeIcon icon={faDroplet} className="icon"/>
              <span>48%</span>
              </p>
              <p id="wind">
              <FontAwesomeIcon icon={faWind} className="icon"/>
              <span>3km/h</span>
              </p>

            </div>
          </div>

        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
